import { combineReducers } from 'redux';


const initialState = {
    departmentRender: '',
    reduxinitialDepUi: '',
    reduxshowSideDrawer: false,
};

const pageReducer = (state=initialState,action) => {
 
  switch (action.type) {
      case 'UPDATE_UIRENDER':
          return {
              ...state,
              departmentRender: action.CopieddepartmentRender
          }
      case 'SIDE_DRAW_TOGGLE_HANDLE':
          return {
                ...state,
                reduxshowSideDrawer: !state.reduxshowSideDrawer            
            }
      case 'BACK_DROP_TOGGLE':
                 return {
                  ...state,
                  reduxshowSideDrawer: !state.reduxshowSideDrawer   
              }
       case 'SIDE_DRAW_CLOSED_TOGGLER':
            return {
                       ...state,
                 reduxshowSideDrawer: false 
                   }
  }
  
  return state;
}


const dataReducer = () => {
    return [
        { title: 'Information Technology', skills: [ "Others",
            "Big Data Analytics",
            "Block Chain",
            "Cloud",
            "Data Science",
            "Databases",
            "Desktop Application",
            "Embedded Systems",
            "Enterprise Application",
            "Game Development",
            "Microservices",
            "Mobiles Apps",
            "Quality Assurance",
            "Tools",
            "Website",
          ] },
{ title: 'Textile', skills: [ "Others",
        "Apparel",
        "Chemical Processing",
        "Draping and Pattern Making",
        "Dyeing",
        "Fashion Technology",
        "Garment Export Merchandising",
        "Interiors Design",
        "Knitwear Design",
        "Man Made Fibre Technology",
        "Mechanical Processing",
        "Quality Control & Testing",
        "Spinning",
        "Weaving",
        "Textile Engineering",
        "Textile Management",
        "Textile Production",
       ] },
{ title: 'Automobile', skills: [ "Others",
        "Automation and Robotics",
        "Automobile Engineering",
        "Four wheeler Jobs",
        "Logistics and Supply Chain",
        "Mechanical Automobile",
        "Quality Control & Testing",
        "Transportation",
        "Two wheeler Jobs",
      ] },
{ title: 'Medical Science', skills: ["Others",
            "Ayurveda",
            "Biomedical",
            "Dentistry",
            "General Medicine",
            "Surgery",
            "Genetic Engineering",
            "Homeopathy",
            "Hospital Management",
            "Medical Electronics",
            "Nursing",
            "Occupational Therapy",
            "Pharmaceutical",
            "Physiotherapy",
          ] },
{ title: 'Marine', skills: [ "Others",
            "Bridge Manoeuvring",
            "Cadet",
            "Engine Control",
            "Hydraulics",
            "Instrumentation & Process Control",
            "Marine Electrical",
            "Naval Architecture & Ocean Engineering",
            "Navigation",
            "Operating Ships",
            "Tanker Cargo",
            "Tester",
          ] },
{ title: 'Business Management', skills: [ "Others",
        "Banking Management",
        "Disaster Management",
        "Entrepreneurship",
        "Finance",
        "Hospitality Management",
        "Human Resource",
        "Insurance",
        "International Business",
        "Marketing",
        "Operation Management",
        "Sales & Marketing",
        "System Management",
      ] },
{ title: "Agriculture & Biology", skills: [  "Others",
        "Agriculture",
        "Food Engineering",
        "Agriculture & Business Management",
        "Applied MicroBiology",
        "Bioinformatics",
        "Botany",
        "Dairy Technology",
        "Food Technology",
        "Forestry Management",
        "Foundry",
        "Irrigation Water Management",
        "Zoology",
      ]},
{ title: 'Electrical & Electronics', skills: [ "Others",
        "Applied Electronics",
        "Control and Instrumentation",
        "Electrical Engineer",
        "Electronics Control Systems",
        "Electronics Engineering",
        "Embedded Systems",
        "High Voltage",
        "Power Electronics and Drives",
        "Power Engineering and Management",
        "Power Systems",
        "Program Logic Controllers",
        "VLSI Design",
       ]},
{ title: 'Chemical', skills: [ "Others",
        "Applied Chemistry",
        "Catalysis Technology",
        "Chemical Engineering",
        "Crystal Science",
        "Leather Technology",
        "Paint Technology",
        "Petrochemical",
        "Polymer",
        "Rubber",
        "Plastic",
      ]},
{ title: 'Communication', skills: [ "Others",
        "Communication Systems",
        "Networking",
        "Sensor Systems",
        "Telecommunication",
        "Wireless Technologies",
      ]},
{ title: 'Civil', skills: [ "Others",
            "Soil Mechanics and Foundation",
            "Applied Geology",
            "Ceramic Engineering",
            "Civil Engineering",
            "Coastal Management",
            "Construction Engineering & Management",
            "Environmental & Management",
            "Geo Informatics",
            "Hydrology & Water Resources",
            "Interior Design",
            "Remote Sensing and Geomatics",
            "Structural",
            "Transportation",
          ]},
{ title: 'Mech & Manufacturing', skills: [ "Others",
        "Green Manufacturing",
        "CAD/CAM",
        "Computer Integrated Manufacturing",
        "Energy Engineering",
        "Energy Management",
        "Hydraulics & Water Res",
        "Industrial Design",
        "Manufacturing Management",
        "Materials Science",
        "Mechanical Engineering",
        "Mechanics",
        "Mechatronics",
        "Mining",
        "Offshore Structures",
        "Printing & Packaging",
        "Product Design & Development",
        "Production & Industrial Engineering",
        "Quality Management",
        "Solar Energy",
        "Solid Fluid Mechanics",
        "Thermal Engineering",
      ]},
{ title: 'Entertainment', skills: [ "Others",
        "Animation and Design",
        "Animation Film Making",
        "Electronic Media",
        "Film Making",
        "Game Art and Design",
        "Graphic Designing",
        "Journalism",
        "Media Management",
        "Multimedia",
        "Visual Communication",
        "Visual Effects",
      ]},
{ title: 'Aerospace', skills: [ "Others",
        "Aeronautical Engineering",
        "Air Traffic Control",
        "AirCraft Manufacturing and Maintenance",
        "Airport Management",
        "Aviation Management",
        "Avionics and Systems",
        "Cabin Crew",
        "Fight Simulation",
        "Helicopters",
        "Pilot",
        "Propulsion",
        "Supply Chain",
      ] },
      { title: 'Physics', skills: [ "Others",
        "Physics Teaching",
        "Medical Physics",
        "Nanotechnology",
        "Nuclear Engineering",
        "Photonics",
      ]},
      { title: 'Maths', skills: [ "Others",
        "Maths Teaching",
        "Industrial Mathematics",
        "Scientific Computing",
        "Applied Mathematics",
        "Business Statistics",
        "Computational Statistics",
        "Maths and Computing Engineering",
      ]},
      { title: 'Arts and Hotel', skills: [ "Others",
        "Catering",
        "Hotel Management",
        "Tourism Management",
        "Commerce",
        "Economics",
        "Earth and Atmospheric",
        "Language Specific",
        "English",
        "Finance",
        "Fine and Performing Arts",
        "History",
        "Law",
        "Physical Education and Sports",
        "Political Science",
      ]},

        ]

}

export default combineReducers ({
    dataExt: dataReducer,
    pageTag: pageReducer
});